import type pg from "pg";

// Ticket 19 (spec §6, §8, §20-21, §77, §205-210): one table for every versioned
// affirmation. The version stored is the version of the wording that was shown,
// so changing the copy is a new version rather than a silent edit.

export type AttestationKind =
  | "data_processing_terms"
  | "ban_risk"
  | "group_responsibility"
  | "tier1_outbound";

// Ticket 21 (spec §21): the wording of every affirmation lives here, one entry
// per kind, and the row stores the text as well as the version. A version is
// never reused for different words — change the words, bump the version — and
// because the text is copied onto the row, editing these constants can no
// longer rewrite what somebody already agreed to.
export const ATTESTATION_TEXTS: Record<AttestationKind, { version: string; text: string }> = {
  // Shown before signup and echoed by POST /v1/signup. Spec §77 + §254: the
  // terms name the region and say plainly that summarisation leaves it.
  data_processing_terms: {
    version: "2026-08-01",
    text:
      "WALAO runs in Singapore (ap-southeast-1) and stores your data there. Messages " +
      "are stored only from groups you explicitly enable, encrypted at rest, and raw " +
      "messages are deleted at the end of your retention window (1-30 days, 7 by " +
      "default). To write a summary, WALAO sends that group's message text to " +
      "Anthropic, an AI provider outside Singapore, which processes it and does not " +
      "keep it. Nobody at WALAO can read your messages or summaries unless you opt " +
      "in to quality review. You can export everything or delete your account at any " +
      "time; deleting destroys your encryption key, so what is left becomes " +
      "unreadable.",
  },
  // Shown before pairing (spec §7-8): the unofficial-gateway risk, named.
  ban_risk: {
    version: "2026-08-01",
    text:
      "Before you pair: WALAO stores messages from groups you explicitly enable, " +
      "encrypted in Singapore (ap-southeast-1), and raw messages auto-expire after " +
      "the retention window. Summaries are generated by Anthropic, an AI provider " +
      "outside Singapore, which processes message text but does not keep it. WALAO " +
      "connects through an unofficial WhatsApp gateway — WhatsApp may disconnect or " +
      "ban numbers using such gateways, and that risk is yours, so beta users " +
      "should pair a dedicated test number. You can disconnect at any time and " +
      "ingestion stops immediately.",
  },
  // Shown when enabling a Group (spec §16, §26). Until ticket 21 this version
  // had no wording behind it at all, which is exactly what §21 forbids.
  group_responsibility: {
    version: "2026-08-02",
    text:
      "You are enabling this group. From now until you disable it, WALAO stores and " +
      "summarises its messages — including messages written by other members, who " +
      "have no account here. That data is processed on your instruction and under " +
      "your responsibility: you confirm you may do this for this group, you will " +
      "tell the other members (there is a one-tap notice you can post), and the " +
      "messages stay only for your retention window. Disabling the group stops " +
      "processing immediately and is recorded too.",
  },
  // Shown when turning on Tier 1 outbound (spec §47-48).
  tier1_outbound: {
    version: "2026-08-02",
    text:
      "Tier 1 lets WALAO send messages from your number to people who are not you. " +
      "Each new recipient first gets one message asking them to reply \"Yes\"; until " +
      "they do, nothing further is sent to them. Sending to people who did not ask " +
      "for it is the most common reason WhatsApp bans a number, and that risk is " +
      "yours, not WALAO's. You authorise these sends and you are responsible for " +
      "what they say.",
  },
};

export const DATA_PROCESSING_TERMS = ATTESTATION_TEXTS.data_processing_terms;

// A pool or an open transaction client — group enable writes its Attestation
// inside the same transaction as the flag flip (spec §209).
type Queryable = Pick<pg.Pool, "query">;

// Version and text come from the registry, never from the caller: the gate that
// checks the echoed version and the row that records it can then never disagree.
// "group_disabled" is the audit row for turning a Group off. It is not an
// affirmation, so it has no entry and carries neither version nor text.
export function recordAttestation(
  db: Queryable,
  userId: string,
  kind: AttestationKind | "group_disabled",
  groupId: string | null = null,
): Promise<unknown> {
  const wording = ATTESTATION_TEXTS[kind as AttestationKind];
  return db.query(
    `INSERT INTO attestations (user_id, kind, version, text, group_id) VALUES ($1, $2, $3, $4, $5)`,
    [userId, kind, wording?.version ?? null, wording?.text ?? null, groupId],
  );
}

export type Attestation = {
  id: string;
  kind: string;
  version: string | null;
  text: string | null;
  group_id: string | null;
  created_at: string;
};

// Spec §20-21: the Account holder can audit their own consent trail, and the
// trail shows the wording as it was shown, not as it reads today.
export async function listAttestations(
  pool: pg.Pool,
  userId: string,
): Promise<Attestation[]> {
  const { rows } = await pool.query(
    `SELECT id, kind, version, text, group_id, created_at
     FROM attestations
     WHERE user_id = $1
     ORDER BY created_at, id`,
    [userId],
  );
  return rows.map((r) => ({ ...r, created_at: new Date(r.created_at).toISOString() }));
}
