import type pg from "pg";
import type { GatewayPort, NormalizedStatus, SessionStatus } from "./gateway/port.ts";

// Shown before pairing. POST /v1/connections must echo the current version
// (same pattern as the group attestation) so pairing cannot start unseen.
export const ONBOARDING_DISCLOSURE = {
  version: "2026-07-30",
  text:
    "Before you pair: WALAO stores messages from groups you explicitly enable, " +
    "encrypted, and raw messages auto-expire after the retention window. " +
    "Summaries are generated by a third-party AI provider that processes message " +
    "text but does not keep it. WALAO connects through an unofficial WhatsApp " +
    "gateway — WhatsApp may disconnect or ban numbers using such gateways, so " +
    "beta users should pair a dedicated test number. You can disconnect at any " +
    "time and ingestion stops immediately.",
};

export type ConnectionView = {
  id: string;
  external_session_id: string;
  status: SessionStatus | "pending";
  status_changed_at: string;
};

function view(r: Record<string, unknown>): ConnectionView {
  return {
    id: r.id as string,
    external_session_id: r.external_session_id as string,
    status: r.status as ConnectionView["status"],
    status_changed_at: new Date(r.status_changed_at as string).toISOString(),
  };
}

export async function createConnection(
  pool: pg.Pool,
  gateway: GatewayPort,
  userId: string,
  disclosureVersion: unknown,
): Promise<"disclosure_required" | { connection: ConnectionView; pairing_code: string }> {
  if (disclosureVersion !== ONBOARDING_DISCLOSURE.version) return "disclosure_required";
  const pairing = await gateway.startPairing();
  const { rows } = await pool.query(
    `INSERT INTO whatsapp_sessions (user_id, external_session_id, status)
     VALUES ($1, $2, 'pending')
     RETURNING id, external_session_id, status, status_changed_at`,
    [userId, pairing.externalSessionId],
  );
  return { connection: view(rows[0]), pairing_code: pairing.pairingCode };
}

export async function listConnections(pool: pg.Pool, userId: string): Promise<ConnectionView[]> {
  const { rows } = await pool.query(
    `SELECT id, external_session_id, status, status_changed_at
     FROM whatsapp_sessions
     WHERE user_id = $1
     ORDER BY created_at`,
    [userId],
  );
  return rows.map(view);
}

// User-initiated disconnect. The user_id predicate is the tenant boundary:
// another user's connection id behaves exactly like a nonexistent one.
export async function disconnectConnection(
  pool: pg.Pool,
  userId: string,
  connectionId: string,
): Promise<"ok" | "not_found"> {
  const n = await transition(
    pool,
    `UPDATE whatsapp_sessions SET status = 'disconnected', status_changed_at = now()
     WHERE id = $1 AND user_id = $2 RETURNING id`,
    [connectionId, userId],
    "disconnected",
  );
  return n === 0 ? "not_found" : "ok";
}

// Gateway-reported state change arriving on the webhook. Unknown session: no-op.
export async function applyGatewayStatus(pool: pg.Pool, evt: NormalizedStatus): Promise<void> {
  await transition(
    pool,
    `UPDATE whatsapp_sessions SET status = $2, status_changed_at = now()
     WHERE external_session_id = $1 RETURNING id`,
    [evt.sessionExternalId, evt.status],
    evt.status,
  );
}

// Flip the session status and keep coverage_gaps consistent in one transaction:
// leaving 'connected' opens a gap (at most one open per session), returning to
// 'connected' closes any open gap. Downstream summary windows overlapping a gap
// are flagged incomplete instead of silently truncated.
async function transition(
  pool: pg.Pool,
  updateSql: string,
  params: unknown[],
  newStatus: SessionStatus,
): Promise<number> {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    const res = await client.query(updateSql, params);
    if (res.rowCount === 0) {
      await client.query("ROLLBACK");
      return 0;
    }
    const sessionId = res.rows[0].id;
    if (newStatus === "connected") {
      await client.query(
        `UPDATE coverage_gaps SET ended_at = now() WHERE session_id = $1 AND ended_at IS NULL`,
        [sessionId],
      );
    } else {
      await client.query(
        `INSERT INTO coverage_gaps (session_id, reason)
         SELECT $1, $2
         WHERE NOT EXISTS
           (SELECT 1 FROM coverage_gaps WHERE session_id = $1 AND ended_at IS NULL)`,
        [sessionId, newStatus],
      );
    }
    await client.query("COMMIT");
    return res.rowCount ?? 0;
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}
